### ISSUE TITLE
The comment of the detect method is difficult to understand

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/Cognitive-Face-Python#26]
Below is the comment of the detect method.

> attributes: [Optional] Analyze and return the one or more specified
            face attributes in the comma-separated string like
            "returnFaceAttributes=age,gender". Supported face attributes
            include age, gender, headPose, smile, facialHair, glasses and
            emotion. Note that each face attribute analysis has additional
            computational and time cost.

quote from [face.py](https://github.com/Microsoft/Cognitive-Face-Python/blob/master/cognitive_face/face.py#L20-L25)

The attributes arg should **be** "age,gender", **not** "returnFaceAttributes=age,gender".
This comment is difficult to understand.

**Comment by huxuan** [comment]
Thanks for your suggestion. That's my fault, I was so lazy that I just blindly copied the API reference description at that time. I will consider to fix it on next release. Any pull requests are also welcome!
