### ISSUE TITLE
Support for 3.x?

### ISSUE THREAD

**Issue by sluongng** [Microsoft/Cognitive-Face-Python#30]
Hi,

It said on https://wxpython.org/ that

> (16-April-2017) wxPython 4.0.0a1 is now available on PyPI. This is the first official release of the new Phoenix version of wxPython, including support for Python 2.7 **and 3.4+**, installation from PyPI, fully self-contained and relocatable so it can be installed in virtual environments, etc.

Should we be expecting a release to support Python 3.6 soon?

**Comment by huxuan** [comment]
Currently, there is no plan to support Python 3 and wxPython 4 as wxPython 4 is still in beta. But I will keep this issue open for future reference.

**Comment by michhar** [comment]
`wxPython` is now in beta.  https://wxpython.org/pages/downloads/index.html  It's also, just a one line of code fix for your project.  See, PR [#48].

**Comment by huxuan** [comment]
With version 1.4.0 finally released. Both WxPython 4 and Python 3 are supported now.

Close this issue and feel free to open new ones if you guys have any concern.
