### ISSUE TITLE
Sample app is crash when uploading image in face detection in Mac OS 10.12.6

### ISSUE THREAD

**Issue by jamesweb1** [Microsoft/Cognitive-Face-Python#37]
I remember it works before. But I want to use the demo app for face detection today, it crashes the app with the following information. My Mac is MacBook Pro 2017 with MacOS 10.12.6. I'm not sure it comes from the recently update of Apple.
------------------------------------
2017-08-15 09:52:44.543 Python[785:19602] *** Assertion failure in void assertRunningOnAppKitThread()(), /Library/Caches/com.apple.xbs/Sources/ViewBridge/ViewBridge-283/ViewBridgeUtilities.m:1045
2017-08-15 09:52:44.549 Python[785:19602] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'not running on AppKit (main) thread'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffb06ff2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffc550f48d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffb0704042 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fffb21b4da6 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   ViewBridge                          0x00007fffc3f5938d -[NSRemoteView _preSuperInit] + 28
	5   ViewBridge                          0x00007fffc3f59793 -[NSRemoteView initWithFrame:] + 25
	6   ViewBridge                          0x00007fffc3f8aaa8 +[NSRemoteViewController requestViewController:withServiceSubclassIdentifier:connectionHandler:withBlock:] + 244
	7   ViewBridge                          0x00007fffc3f8b04c +[NSRemoteViewController requestViewController:fromServiceListenerEndpoint:connectionHandler:] + 78
	8   HIToolbox                           0x00007fffafe41841 -[IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler:] + 1760
	9   HIToolbox                           0x00007fffafe36b39 __80-[IMKInputSession imkxpc_presentFunctionRowItemTextInputViewWithEndpoint:reply:]_block_invoke + 538
	10  CoreFoundation                      0x00007fffb069517c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	11  CoreFoundation                      0x00007fffb0675f84 __CFRunLoopDoBlocks + 356
	12  CoreFoundation                      0x00007fffb0675ac6 __CFRunLoopRun + 1878
	13  CoreFoundation                      0x00007fffb0675114 CFRunLoopRunSpecific + 420
	14  HIToolbox                           0x00007fffafe1219e -[IMKInputSessionXPCInvocation invocationAwaitXPCReply] + 606
	15  HIToolbox                           0x00007fffafe14750 -[IMKInputSession activate] + 3471
	16  HIToolbox                           0x00007fffafdc87ab IMKInputSessionActivate + 36
	17  HIToolbox                           0x00007fffafdc7b3c ActivateInputMethodInstance + 100
	18  HIToolbox                           0x00007fffafdbc4ca utOpenActivateSelectedInputMethodInDoc + 369
	19  HIToolbox                           0x00007fffafdbc334 utOpenActivateAllSelectedIMInDocIterator + 21
	20  CoreFoundation                      0x00007fffb0637e34 CFArrayApplyFunction + 68
	21  HIToolbox                           0x00007fffafbf1384 utOpenActivateAllSelectedIMInDoc + 187
	22  HIToolbox                           0x00007fffafbe9ee8 MyActivateTSMDocument + 1910
	23  AppKit                              0x00007fffae2b288d -[NSTextInputContext activate] + 284
	24  AppKit                              0x00007fffaeb43ec2 +[NSTextInputContext currentInputContext_withFirstResponderSync:] + 362
	25  AppKit                              0x00007fffae252060 -[NSTextView(NSSharing) setEditable:] + 250
	26  libwx_osx_cocoau_core-3.0.dylib     0x0000000105c7001b _ZN19wxNSTextViewControl9WriteTextERK8wxString + 57
	27  libwx_osx_cocoau_core-3.0.dylib     0x0000000105bfecaa _ZN11wxTextEntry9WriteTextERK8wxString + 84
	28  _core_.so                           0x000000010491427d _Z29_wrap_TextEntryBase_WriteTextP7_objectS0_S0_ + 194
	29  Python                              0x00000001045280ac PyEval_EvalFrameEx + 13560
	30  Python                              0x00000001045249be PyEval_EvalCodeEx + 1617
	31  Python                              0x000000010452b3e2 _PyEval_SliceIndex + 338
	32  Python                              0x0000000104527e4e PyEval_EvalFrameEx + 12954
	33  Python                              0x000000010452b475 _PyEval_SliceIndex + 485
	34  Python                              0x0000000104527e4e PyEval_EvalFrameEx + 12954
	35  Python                              0x00000001045249be PyEval_EvalCodeEx + 1617
	36  Python                              0x00000001044ca4d1 PyFunction_SetClosure + 826
	37  Python                              0x00000001044ac6fb PyObject_Call + 99
	38  Python                              0x0000000104527fe5 PyEval_EvalFrameEx + 13361
	39  Python                              0x000000010452b475 _PyEval_SliceIndex + 485
	40  Python                              0x0000000104527e4e PyEval_EvalFrameEx + 12954
	41  Python                              0x000000010452b475 _PyEval_SliceIndex + 485
	42  Python                              0x0000000104527e4e PyEval_EvalFrameEx + 12954
	43  Python                              0x00000001045249be PyEval_EvalCodeEx + 1617
	44  Python                              0x00000001044ca4d1 PyFunction_SetClosure + 826
	45  Python                              0x00000001044ac6fb PyObject_Call + 99
	46  Python                              0x00000001044b73ac PyMethod_New + 1221
	47  Python                              0x00000001044ac6fb PyObject_Call + 99
	48  Python                              0x000000010452adbb PyEval_CallObjectWithKeywords + 165
	49  Python                              0x0000000104557d4e initthread + 2833
	50  libsystem_pthread.dylib             0x00007fffc600e93b _pthread_body + 180
	51  libsystem_pthread.dylib             0x00007fffc600e887 _pthread_body + 0
	52  libsystem_pthread.dylib             0x00007fffc600e08d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by huxuan** [comment]
It works on my workstation. I wonder which kind of python are you using? The latest homebrew version seems to wrok for me.

**Comment by jamesweb1** [comment]
I use the the apple build-in python 2.7. Are you the same OS as mime?

**Comment by huxuan** [comment]
Yep, the latest version of MacOS.

Also please also pay a little attention on the package version. I think this repo only support old version of wxpython now which should be 3.0.2.0.

**Comment by jamesweb1** [comment]
>>> import wx
>>> wx.__version__
'3.0.2.0'

Yes, I'm using 3.0.2.0

**Comment by huxuan** [comment]
Then would you please have a try on the brewed python? That might be helpful.

**Comment by jamesweb1** [comment]
I found I can use it with 'sudo python sample.py', but get the error by 'python sample.py'...I cannot find out the root cause. Because I'm sure I'm using the same wxpython 3.0.2.0.

Print in the program: /usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/__init__.pyc (no matter sudo or not)

**Comment by huxuan** [comment]
It looks like a system permission problem. That is why I suggest to use brewed python. :-)
Anyway, good to know the problem solved.

Close the issue as problem solved.
