### ISSUE TITLE
Attirbutes for face.detect() - documentation clarification

### ISSUE THREAD

**Issue by thezelus** [Microsoft/Cognitive-Face-Python#43]
[https://github.com/Microsoft/Cognitive-Face-Python/blob/master/cognitive_face/face.py#L14](https://github.com/Microsoft/Cognitive-Face-Python/blob/master/cognitive_face/face.py#L14) comment here can become more helpful if additional attributes can be added.

`"age,gender,headPose,smile,facialHair,glasses,emotion,makeup,hair,accessories"`

Also, not sure if this is the right place to mention this but in the [https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236](official documentation) `faceAttributes` include `accessory` as a param but when using that it returns a Bad Request response. The correct attribute is `accessories`

**Comment by huxuan** [comment]
Thanks for the reporting, we will look over all related place to avoid similar problems. Just enjoy Face API.

**Comment by huxuan** [comment]
This is an update for fixing all related bugs, both for Python doc and API reference. But it still takes some time before next release (as it is not a functional bug). Thanks again for the reporting and issue closed as resolved.
