### ISSUE TITLE
test fail..

### ISSUE THREAD

**Issue by protik3380** [Microsoft/Cognitive-Face-Python#45]
![screenshot from 2017-10-19 23-39-49](https://user-images.githubusercontent.com/25229309/31785393-e01e23b4-b526-11e7-880e-a041c53b8b93.png)

**Comment by cthrash** [comment]
Please see [this](https://github.com/Microsoft/Cognitive-Face-Python/blob/c9048b68878c0ca7db5dec075b38a4ba6a1c5eb4/README.md#L24).
You need to specify a base URL that is terminated with a `/`.

**Comment by huxuan** [comment]
Yep, @cthrash is right. I will fix this kind of problem in the next release. Closed as problem should be solved.
