### ISSUE TITLE
Suggestion: support proxy

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/Cognitive-Face-Python#49]
I usually develop application in environment under proxy.
Please support proxy.

The following coding style may be good.

```python
import cognitive_face as CF
CF.Proxy.set('proxy')
```

**Comment by huxuan** [comment]
Hi @YuichiNukiyama, actually this Python Wrapper is try to keep a slim size and proxy may not be an expected feature on the road map. I suggest you use different approach, for example, inject the `requests` module directly.
