### ISSUE TITLE
API errror:  'message: Invalid argument returnFaceAttributes.'

### ISSUE THREAD

**Issue by pwna5aurus** [Microsoft/Cognitive-Face-Python#51]
Is this now unsupported API functionality?  Have not been able to return attributes.

**Comment by huxuan** [comment]
Hi @pwna5aurus, what do you assign to the `returnFaceAttributes` parameter. It should be a raw string in format of something like `age,gender`

**Comment by pwna5aurus** [comment]
I tried (arg1, returnFaceAttributes='age, gender'), (arg1, attributes='age,
gender')...both returned an error.

**Comment by pwna5aurus** [comment]
Tried it without the space:
`result = CF.face.detect(fp,attributes='age,gender, headPose, smile, facialHair, glasses, emotion, hair, makeup, occlusion, accessories, blur, exposure, noise')`

Here is the error:

```
File "test.py", line 11, in <module>
    result = CF.face.detect(fp,attributes='age,gender, headPose, smile, facialHair, glasses, emotion, hair, makeup, occlusion, accessories, blur, exposure, noise')
  File "C:\Python27\lib\site-packages\cognitive_face\face.py", line 41, in detect
    'POST', url, headers=headers, params=params, json=json, data=data)
  File "C:\Python27\lib\site-packages\cognitive_face\util.py", line 106, in request
    error_msg.get('message'))
cognitive_face.util.CognitiveFaceException: Error when calling Cognitive Face API:
        status_code: 400
        code: BadArgument
        message: Invalid argument returnFaceAttributes.
```

**Comment by huxuan** [comment]
@pwna5aurus , there should be **no space after all the commas**. For example, it should be `age,gender,headPose,smile,facialHair,glasses,emotion,hair,makeup,occlusion,accessories,blur,exposure,noise`

**Comment by huxuan** [comment]
Closed as explained and no further response, please feel free to reopen it if there is any further questions.
