### ISSUE TITLE
ModuleNotFoundError: No module named '------'

### ISSUE THREAD

**Issue by SerkanEkremCengiz** [Microsoft/Cognitive-Face-Python#52]
import util
ModuleNotFoundError: No module named 'util'

from view.panel_detection import DetectionPanel
ModuleNotFoundError: No module named 'view.panel_detection'; 'view' is not a package

I have been having problems with almost all import "---". What should I do?

<img width="474" alt="ekran resmi 2018-07-10 09 04 03" src="https://user-images.githubusercontent.com/26429016/42494265-6ade5e1c-8428-11e8-97b8-446fa1747f19.png">

**Comment by huxuan** [comment]
Please try to run the sample according to the instruction here: https://github.com/Microsoft/Cognitive-Face-Python#running-the-sample

**Comment by SerkanEkremCengiz** [comment]
I want to debug with these codes and see how these codes work(for example: Panel_identification.py). I don't want to run the sample directly.

**Comment by huxuan** [comment]
I do not think it is a common pattern to investigate Python code and you may need to use some kind of IDE instead (I have no experience). Running directly against the specific python file will definitely lead to this kind of relative import error.

**Comment by huxuan** [comment]
Closed as explained, please feel free to reopen it if there is any further question.
