### ISSUE TITLE
Minimum Working example without UI?

### ISSUE THREAD

**Issue by CT83** [Microsoft/Cognitive-Face-Python#54]
There is a GUI Application in the Repo but there is not a simple minimum working example for Face Identification. 
The GUI Application intimidated me as I started to look into it, as a beginner myself.
I would like to make a PR of something like this [Simple Working Example](https://gist.github.com/CT83/98f257e00651efcdea65f31ea9c9a743), of course after cleaning it up.

Would this be a good idea?
Yes, I have read the Contributing Guidelines, which state that UI needs to be included. But would a Simple Working Example make things easier?

**Comment by huxuan** [comment]
Does the [tests](https://github.com/Microsoft/Cognitive-Face-Python/tree/master/cognitive_face/tests) meet your needs for the example?

**Comment by CT83** [comment]
@huxuan Actually they do! Thanks! It didn't occur to me to look into tests. Sorry about that. 
Closing Issue.
