### ISSUE TITLE
Outdated endpoint

### ISSUE THREAD

**Issue by neroksi** [microsoft/Cognitive-Face-Python#66]
I've tried the package today and it doesn't work for me. The error message is below : 

```
KeyError                                  Traceback (most recent call last)

import cognitive_face  as cf
cf.Key.set(key)
cf.BaseUrl.set(baseUrl)

group_id = "myfriends5"
group_name = "My friends"
group_data = "No data added for instant"
group = cf.person_group.create(group_id, group_name, group_data)

cognitive_face\util.py in request(method, url, data, json, headers, params)
    101         try:
--> 102             error_msg = response.json()['error']
    103         except:

KeyError: 'error'

During handling of the above exception, another exception occurred:

CognitiveFaceException                    Traceback (most recent call last)
<ipython-input-5-c52595173f41> in <module>()
      2 group_name = "My friends"
      3 group_data = "No data added for instant"
----> 4 group = cf.person_group.create(group_id, group_name, group_data)

cognitive_face\person_group.py in create(person_group_id, name, user_data)
     31     }
     32 
---> 33     return util.request('PUT', url, json=json)
     34 
     35 

\cognitive_face\util.py in request(method, url, data, json, headers, params)
    103         except:
    104             raise CognitiveFaceException(response.status_code,
--> 105                                          response.status_code, response.text)
    106         raise CognitiveFaceException(response.status_code,
    107                                      error_msg.get('code'),

CognitiveFaceException: Error when calling Cognitive Face API:
	status_code: 404
	code: 404
	message: { "statusCode": 404, "message": "Resource not found" }
```

It takes much time to figure out what is the problem : currently, urls passed to `request()` are not well parsed. Instead of `url = 'persongroups/{}'.format(person_group_id)` we must have `url = "face/v1.0/persongroups/{}".format(person_group_id)`. Things worked for me when I clone the repo and modifies the urls.

**Comment by acured** [comment]
Yes,  endpoint looks like "https://[location].api.cognitive.microsoft.com/face/v1.0". Reference [here](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236).

Have you still got "KeyError: 'error'" after modified the url?

**Comment by neroksi** [comment]
@acured No, there was no error after changing the url. Could you expose the `endpoint' as an argument? Because it's quite volatile and will probably change over time.

**Comment by acured** [comment]
cf.BaseUrl.set(baseUrl) will help you to change the endpoint.

**Comment by lebronJ** [comment]
Close this since there is no more response. Feel free to reopen this if further concerns.
