### ISSUE TITLE
Length of faceId is not in Valid Range

### ISSUE THREAD

**Issue by SMe12435** [microsoft/Cognitive-Face-Python#68]
Microsoft by default sets maximum length of faceIds to 20 whereas the limit is 1000. I want to increase it. I am unable to resolve the issue. Thanks for the help in advace!!

**Comment by lebronJ** [comment]
Which operations are you using?

**Comment by SMe12435** [comment]
I am using CF.face.detect('image.jpg')

**Comment by lebronJ** [comment]
Can you clarify this? Which operation are you calling the faceIds and meeting with this limitation?

**Comment by SMe12435** [comment]
Basically, I have added faces for training in PersonGroup. After the training is done I want to detect those people in the image(attached
![smeclass](https://user-images.githubusercontent.com/25767954/54474458-107d5480-480b-11e9-8568-38e158a765be.jpg)
)
But as the image has more than 20 faces I am unable to get more than 20 faceIds. 
![Screenshot from 2019-03-16 16-47-30](https://user-images.githubusercontent.com/25767954/54474480-52a69600-480b-11e9-8d47-6f6b687609b0.png)

The above image was taken from - https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395237

**Comment by lebronJ** [comment]
Do you mean FindSimilar declares returning at most 1000 faces but actually no more than 20?

If yes, this is a known issue and we are going to fixing that in next release in about 1-2 weeks, please check it back then. Sorry for the inconvenience.

**Comment by SMe12435** [comment]
Yes, that is the problem that I am facing. Is this an issue only in python or in C# as well??

**Comment by lebronJ** [comment]
It’s a known bug of Face API, thus for SDKs of all languages.

**Comment by lebronJ** [comment]
We will update this issue as soon as we fix it. Well I think the problem only exists for FindSimilar towards FaceList or LargeFaceList. Please check the API reference to see if Identify towards PersonGroup or LargePersonGroup is your actual need.

**Comment by SMe12435** [comment]
Okay! Thanks for the help sir. Looking forward to a fix soon! I'd be happy if you acknowledge once the issue is fixed. :+1:

**Comment by SMe12435** [comment]
I have written this set of code in python. 


`#importing libraries to crop out faces for train. I am taking 30 images and training it at FACE API server
import cv2
import time
import dlib
import os

#cognitive face library microsoft.
import cognitive_face as CF

#taking feed from camera
cap = cv2.VideoCapture(0)

#face_detector
detector = dlib.get_frontal_face_detector()


#Azure key
SUBSCRIPTION_KEY ='------------------'
BASE_URL = 'https://centralindia.api.cognitive.microsoft.com/face/v1.0'
CF.BaseUrl.set(BASE_URL)
CF.Key.set(SUBSCRIPTION_KEY)




#Person group id 
PERSON_GROUP_ID = 'tttt0'

#CF.person_group.create(PERSON_GROUP_ID, 'ttt 0')



#this print command is only for testing
print(CF.person.lists(PERSON_GROUP_ID))


#taking input from user..
name = input("Please Enter Your Name\t")
user_data = input("Enter Registration Number\t")



response = CF.person.create(PERSON_GROUP_ID, name, user_data)

#Get person_id from response only for testing
person_id = response['personId']
print(person_id)

#storing images for future reference.
Id = user_data
#Click and Train
folderName = "user" + Id                                                        # creating the person or user folder
folderPath = os.path.join(os.path.dirname(os.path.realpath(__file__)), "dataset/"+folderName)
if not os.path.exists(folderPath):
    os.makedirs(folderPath)

sampleNum = 0
while(True):
    ret, img = cap.read()                                                       # reading the camera input
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)                                # Converting to GrayScale
    dets = detector(img, 1)
    for i, d in enumerate(dets):                                                # loop will run for each face detected
        sampleNum += 1
        cv2.imwrite(folderPath+"/"+str(sampleNum) + ".jpg",
                    img[d.top():d.bottom(), d.left():d.right()])                                                # Saving the faces
        cv2.rectangle(img, (d.left(), d.top())  ,(d.right(), d.bottom()),(0,255,0) ,2) # Forming the rectangle
        cv2.waitKey(200)                                                        # waiting time of 200 milisecond
    cv2.imshow('frame', img)                                                    # showing the video input from camera on window
    cv2.waitKey(1)
    if(sampleNum >= 20):                                                        # will take 20 faces
        break


SampleNum =0
while(SampleNum<20):
	CF.person.add_face(folderPath+"/"+str(sampleNum) + ".jpg", PERSON_GROUP_ID, person_id)
	CF.person_group.train(PERSON_GROUP_ID)
	SampleNum += 1
	time.sleep(2)`

**Comment by SMe12435** [comment]
I have written a code to add people to my FACE API

Created on Sun Jan 20 18:13:18 2019

@author: sme
"""


#importing libraries
import cv2
import time
import dlib
import os
#cognitive face library microsoft.
import cognitive_face as CF
#taking feed from camera
cap = cv2.VideoCapture(0)
#face_detector
detector = dlib.get_frontal_face_detector()
#Azure key
SUBSCRIPTION_KEY = '14f0246583d34ffab817e30713313cdf'
BASE_URL = 'https://centralindia.api.cognitive.microsoft.com/face/v1.0'
CF.BaseUrl.set(BASE_URL)
CF.Key.set(SUBSCRIPTION_KEY)
#ye jo person group id hai... ye har class ke liye alag hoga...
PERSON_GROUP_ID = 'tttt0'
#CF.person_group.create(PERSON_GROUP_ID, 'ttt 0')
#this print command is only for testing
print(CF.person.lists(PERSON_GROUP_ID))
#taking input from user.. joki tu textbox se lega..
name = input("Please Enter Your Name\t")
user_data = input("Enter Registration Number\t")
response = CF.person.create(PERSON_GROUP_ID, name, user_data)
# Get person_id from response only for testing
person_id = response['personId']
print(person_id)
Id = user_data
#Click and Train
folderName = "user" + Id                                                        # creating the person or user folder
folderPath = os.path.join(os.path.dirname(os.path.realpath(__file__)), "dataset/"+folderName)
if not os.path.exists(folderPath):
    os.makedirs(folderPath)

sampleNum = 0
while(True):
    ret, img = cap.read()                                                       # reading the camera input
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)                                # Converting to GrayScale
    dets = detector(img, 1)
    for i, d in enumerate(dets):                                                # loop will run for each face detected
        sampleNum += 1
        cv2.imwrite(folderPath+"/"+str(sampleNum) + ".jpg",
                    img[d.top():d.bottom(), d.left():d.right()])                                                # Saving the faces
        cv2.rectangle(img, (d.left(), d.top())  ,(d.right(), d.bottom()),(0,255,0) ,2) # Forming the rectangle
        cv2.waitKey(200)                                                        # waiting time of 200 milisecond
    cv2.imshow('frame', img)                                                    # showing the video input from camera on window
    cv2.waitKey(1)
    if(sampleNum >= 20):                                                        # will take 20 faces
        break


SampleNum =0
while(SampleNum<20):
	CF.person.add_face(folderPath+"/"+str(sampleNum) + ".jpg", PERSON_GROUP_ID, person_id)
	CF.person_group.train(PERSON_GROUP_ID)
	SampleNum += 1
	time.sleep(2)








#training model with all the images
#CF.person.add_face('test.jpg', PERSON_GROUP_ID, person_id)
#print CF.person.lists(PERSON_GROUP_ID)


response = CF.person_group.get_status(PERSON_GROUP_ID)
status = response['status']

print(status)

**Comment by SMe12435** [comment]
I don't detecting a person group is what I am looking for. I am looking forward to detecting each face in a PersonGroup.

**Comment by lebronJ** [comment]
This bug has been fixed for long time, sorry for forgetting updating the status right after the fix.

I will close this issue, feel free to reopen this thread if any further concerns.
