### ISSUE TITLE
Error when using add_face

### ISSUE THREAD

**Issue by yexing99** [Microsoft/Cognitive-Face-Python#70]
I am trying to add one photo to a person_group

name = "Alice"
user_data = 'More information can go here'
response = CF.person.create(PERSON_GROUP_ID, name, user_data)
person_id = response['personId']
CF.person.add_face('/Images/IMG_0325.jpg', PERSON_GROUP_ID, person_id)**

But I got the following error. Can someone help?
CognitiveFaceException: Error when calling Cognitive Face API:
	status_code: 400
	code: InvalidURL
	message: Invalid image URL.

**Comment by lebronJ** [comment]
I think currently we only support absolute file path for local images. Could you try with it?

**Comment by yexing99** [comment]
Tried the absolute file path but also failed

**Comment by acured** [comment]
Hi @yexing99 

I think you have to use an image stream to avoid this.

[Here](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/face/face/detectwithurl) has some description on this image **url**(Publicly reachable URL of an image) which means you can't using a local file path to do this. Or you can upload your image to an public reachable area, then you can pass the url.

**Comment by yexing99** [comment]
yes, absolute file path can work. Thank you
